import type { DashboardColorSet } from "@/types/profile";

export interface DashboardThemePreset {
  id: string;
  name: string;
  previewColors: [string, string, string]; // [primary, accent, bg]
  light: DashboardColorSet;
  dark: DashboardColorSet;
}

export const DASHBOARD_THEME_PRESETS: DashboardThemePreset[] = [
  // ── 01 MARFIL — Teal institucional, neutros cálidos ───────────────────────
  {
    id: "marfil",
    name: "Marfil",
    previewColors: ["#173B45", "#3fb8a8", "#f7f6f1"],
    light: {
      background:       "#f7f6f1",
      surface:          "#fdfcf9",
      surfaceMuted:     "#efeee9",
      surfaceElevated:  "#ffffff",
      primary:          "#173B45",
      primaryForeground:"#ffffff",
      accent:           "#3fb8a8",
      text:             "#102A33",
      textMuted:        "#5a6e76",
      border:           "#dddbd4",
      success:          "#2e6e48",
      successForeground:"#d6f0e2",
      warning:          "#8a5e14",
      error:            "#a83030",
      ring:             "#3fb8a8",
    },
    dark: {
      background:       "#161e20",
      surface:          "#1e2a2e",
      surfaceMuted:     "#263236",
      surfaceElevated:  "#2e3c42",
      primary:          "#3fb8a8",
      primaryForeground:"#0e1a1e",
      accent:           "#5fd0c0",
      text:             "#d4e6ea",
      textMuted:        "#6a8e9a",
      border:           "#2a3a40",
      success:          "#3a9060",
      successForeground:"#c8ead8",
      warning:          "#b88a30",
      error:            "#c85858",
      ring:             "#5fd0c0",
    },
  },

  // ── 02 MARINO — Azul oceánico, autoridad clínica ──────────────────────────
  {
    id: "marino",
    name: "Marino",
    previewColors: ["#1e3a5f", "#3a7ec4", "#f2f5f8"],
    light: {
      background:       "#f2f5f8",
      surface:          "#fafcfd",
      surfaceMuted:     "#e6edf4",
      surfaceElevated:  "#ffffff",
      primary:          "#1e3a5f",
      primaryForeground:"#ffffff",
      accent:           "#3a7ec4",
      text:             "#0f2035",
      textMuted:        "#426080",
      border:           "#ccd8e8",
      success:          "#256042",
      successForeground:"#d0eedd",
      warning:          "#8a6010",
      error:            "#a03030",
      ring:             "#3a7ec4",
    },
    dark: {
      background:       "#121c28",
      surface:          "#192436",
      surfaceMuted:     "#202e42",
      surfaceElevated:  "#283a50",
      primary:          "#5a9ad8",
      primaryForeground:"#0a1420",
      accent:           "#7ab8f0",
      text:             "#ccdcf0",
      textMuted:        "#6080a0",
      border:           "#1e3050",
      success:          "#347a52",
      successForeground:"#c0e2d0",
      warning:          "#b08a28",
      error:            "#c85050",
      ring:             "#7ab8f0",
    },
  },

  // ── 03 VERDE — Bosque orgánico, bienestar ─────────────────────────────────
  {
    id: "verde",
    name: "Verde",
    previewColors: ["#1a5c3a", "#2ea86a", "#f1f6f2"],
    light: {
      background:       "#f1f6f2",
      surface:          "#fafcfa",
      surfaceMuted:     "#e2ede6",
      surfaceElevated:  "#ffffff",
      primary:          "#1a5c3a",
      primaryForeground:"#ffffff",
      accent:           "#2ea86a",
      text:             "#0d3020",
      textMuted:        "#3a5e48",
      border:           "#c4daca",
      success:          "#1a6030",
      successForeground:"#ccecd8",
      warning:          "#7a6010",
      error:            "#9a2828",
      ring:             "#2ea86a",
    },
    dark: {
      background:       "#101c14",
      surface:          "#162418",
      surfaceMuted:     "#1e2e20",
      surfaceElevated:  "#263a28",
      primary:          "#3ab87a",
      primaryForeground:"#081408",
      accent:           "#5ed096",
      text:             "#c8e4d0",
      textMuted:        "#5a8868",
      border:           "#1c3022",
      success:          "#32904e",
      successForeground:"#c0e2cc",
      warning:          "#b08828",
      error:            "#c05050",
      ring:             "#5ed096",
    },
  },

  // ── 04 ROSA — Empolvado sobrio, estética y belleza ────────────────────────
  {
    id: "rosa",
    name: "Rosa",
    previewColors: ["#7a3050", "#c86890", "#f8f2f4"],
    light: {
      background:       "#f8f2f4",
      surface:          "#fdf8fa",
      surfaceMuted:     "#efe0e8",
      surfaceElevated:  "#ffffff",
      primary:          "#7a3050",
      primaryForeground:"#ffffff",
      accent:           "#c86890",
      text:             "#3a1020",
      textMuted:        "#7a4860",
      border:           "#e4c8d8",
      success:          "#2e6040",
      successForeground:"#cce8d8",
      warning:          "#8a6010",
      error:            "#a02828",
      ring:             "#c86890",
    },
    dark: {
      background:       "#1e1218",
      surface:          "#281820",
      surfaceMuted:     "#34202a",
      surfaceElevated:  "#402a36",
      primary:          "#c87898",
      primaryForeground:"#160810",
      accent:           "#e098b0",
      text:             "#f0d8e4",
      textMuted:        "#a07090",
      border:           "#3e2030",
      success:          "#3a7a50",
      successForeground:"#c0dccb",
      warning:          "#b08830",
      error:            "#c85868",
      ring:             "#e098b0",
    },
  },

  // ── 05 GRAFITO — Monocromático azulado, máxima sobriedad ─────────────────
  {
    id: "grafito",
    name: "Grafito",
    previewColors: ["#27272a", "#52525b", "#f3f4f5"],
    light: {
      background:       "#f3f4f5",
      surface:          "#fafafa",
      surfaceMuted:     "#e6e8ea",
      surfaceElevated:  "#ffffff",
      primary:          "#27272a",
      primaryForeground:"#ffffff",
      accent:           "#52525b",
      text:             "#18181b",
      textMuted:        "#52525b",
      border:           "#d2d4d8",
      success:          "#286040",
      successForeground:"#cceadb",
      warning:          "#8a6010",
      error:            "#9a2828",
      ring:             "#52525b",
    },
    dark: {
      background:       "#16181c",
      surface:          "#1e2026",
      surfaceMuted:     "#26292f",
      surfaceElevated:  "#2e3138",
      primary:          "#a0a8b4",
      primaryForeground:"#0e1014",
      accent:           "#c0c8d4",
      text:             "#e4e6ea",
      textMuted:        "#7880a0",
      border:           "#2c2f38",
      success:          "#388a58",
      successForeground:"#c0ddd0",
      warning:          "#b08828",
      error:            "#c85858",
      ring:             "#a0a8b4",
    },
  },

  // ── 06 ARENA — Ocres cálidos, spa y wellness ──────────────────────────────
  {
    id: "arena",
    name: "Arena",
    previewColors: ["#6a4c2e", "#c49060", "#f6f3ee"],
    light: {
      background:       "#f6f3ee",
      surface:          "#fdfbf7",
      surfaceMuted:     "#ede8de",
      surfaceElevated:  "#ffffff",
      primary:          "#6a4c2e",
      primaryForeground:"#ffffff",
      accent:           "#c49060",
      text:             "#2e1e0e",
      textMuted:        "#7a5e3a",
      border:           "#dfd0b8",
      success:          "#2e6040",
      successForeground:"#cceadb",
      warning:          "#8a5e10",
      error:            "#9a2828",
      ring:             "#c49060",
    },
    dark: {
      background:       "#1c1510",
      surface:          "#241c14",
      surfaceMuted:     "#2e241a",
      surfaceElevated:  "#3a2e20",
      primary:          "#c49060",
      primaryForeground:"#120e08",
      accent:           "#dab07a",
      text:             "#f0e4d0",
      textMuted:        "#a88060",
      border:           "#382a1c",
      success:          "#3a7850",
      successForeground:"#c2dcc8",
      warning:          "#b88830",
      error:            "#c05858",
      ring:             "#dab07a",
    },
  },
];

export const DEFAULT_THEME_ID = "marfil";

export function getThemePreset(id: string): DashboardThemePreset {
  return DASHBOARD_THEME_PRESETS.find((t) => t.id === id) ?? DASHBOARD_THEME_PRESETS[0];
}
